
image: gitpod/workspace-full:latest

tasks:
  - init: npm install
    command: echo "Welcome to your Gitpod workspace!"

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode

ports:
  - port: 3000
    onOpen: open-preview
